name: Sintonize Tests

on:
  push:
    branches:
      - '**'

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: sintonize
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout test repo
        uses: actions/checkout@v4

      - name: Clone backend repo (para pegar o requirements.txt)
        run: |
          git clone https://github.com/ProjetoSafira/Sintonize.git backend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Apply Django migrations
        run: python backend/manage.py migrate

      - name: Start Django server
        run: |
          nohup python backend/manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &

      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "✅ Backend is ready!"
              exit 0
            else
              echo "⏳ Waiting for backend... ($i)"
              sleep 5
            fi
          done
          echo "❌ Backend did not become ready in time."
          cat server.log
          exit 1

      - name: Install Node dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Show Django server logs (if failed)
        if: failure()
        run: cat server.log
