name: Sintonize Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependecies
        run: npm install

      - name: Run E2E tests
        run: npm run cypress:run
