name: Sintonize Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: sintonize
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download requirements.txt
        run: curl -o requirements.txt https://raw.githubusercontent.com/ProjetoSafira/Sintonize/main/requirements.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply Django migrations
        run: python manage.py migrate

      - name: Start Django server
        run: python manage.py runserver 0.0.0.0:8000 &

      - name: Wait for backend to be ready
        run: npx wait-on http://127.0.0.1:8000

      - name: Install Node dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

